### ISSUE TITLE
How to increase disk space in /dev/sda1

### ISSUE THREAD

**Issue by xujiew** [ilbers/isar#101]
Hi,

I am running the built image in qemu via start_vm script and trying to run a few tests such as installing packages, etc. While trying to install podman via apt I got the following error

```
ln: failed to create hard link '/boot/initrd.img-6.1.0-15-amd64.dpkg-bak' => '/boot/initrd.img-6.1.0-15-amd64': Operation not permitted
cp: error copying '/boot/initrd.img-6.1.0-15-amd64' to '/boot/initrd.img-6.1.0-15-amd64.dpkg-bak': No space left on device
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Where it suggests that /dev/sda1 space is full
```
Filesystem     1K-blocks    Used Available Use% Mounted on
udev              467348       0    467348   0% /dev
tmpfs              97836     808     97028   1% /run
/dev/sda2        8071088 2912484   4785248  38% /
tmpfs             489172     112    489060   1% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
/dev/sda1          61174   61174         0 100% /boot
tmpfs              97832       0     97832   0% /run/user/0
```
Is there any way to increase that disk size in the image build?

Some build parameters listed below:
```
Distro = Debian bookworm
Machine = qemuamd64
Image type = base
Image FS type=wic
```

Thanks!

**Comment by amikan** [comment]
Hello @xujiew,

Partition layout for `qemuamd64` machine is set by `meta-isar/scripts/lib/wic/canned-wks/sdimage-efi.wks` file where you can add `--size` option to specify the size you need for any partition. Or you can create your custom wks file.
See [Yocto Project Reference Manual](https://docs.yoctoproject.org/ref-manual/kickstart.html) for details.

P.S. We are using [mailling list](https://github.com/ilbers/isar#support) for this project, please put your questions there next time.

**Comment by xujiew** [comment]
Thank you for the quick respond! Updated that file and it worked. 

And noted, will use the mailing list for future questions.
