### ISSUE TITLE
Add user with bash

### ISSUE THREAD

**Issue by SCordibella** [ilbers/isar#103]
Dear All, I am trying to add a user following the example reported in `user-isar.yaml` file.

The problem is that the new user has sh as shell and I want to create it with `/usr/bin/bash`.
I tried different user flags, but no one works.

Are there any documentation about the syntax to use? 

Best regards,
Stefano.

**Comment by WiseLord** [comment]
Hello.
You could try something like
```
USER_isar[shell] = "/bin/bash"
```
Also, other available options are self-documented in `meta/classes/image-account-extension.bbclass`.

**Comment by SCordibella** [comment]
Thank you @WiseLord it works as expected.

**Comment by jan-kiszka** [comment]
We should still consider lifting this code-level documentation into the user manual - given that there is not even a link from the manual to that code.

**Comment by WiseLord** [comment]
We actually have it documented at https://github.com/ilbers/isar/blob/master/doc/user_manual.md#user-and-group-configuration
But it may be a bit find to find since it's not reflected in the `Contents`.

**Comment by jan-kiszka** [comment]
So, what's missing in the manual are the examples - better move them from the code to the manual.
