### ISSUE TITLE
Multiconfig build of different suites for the same machine doesn't work

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#13]
E.g., `bitbake multiconfig:qemuarm-wheezy:isar-image-base multiconfig:qemuarm-jessie:isar-image-base` fails in `isar-image-base.bb` with the following error:

```
cp: cannot stat ‘/home/ibr/w/work/j/isar/src/b-master-1/tmp/work/isar-image-base/qemuarm/rootfs/boot/vmlinuz-3.2.0-4-vexpress’: No such file or directory
```

`tmp/work/isar-image-base/qemuarm` is used for both wheezy and jessie.

**Comment by alexbluesman** [comment]
Fixed in commit: 1f27b7f7927cbf2bb0317a05fd1ad0d13dd03c1b
