### ISSUE TITLE
Support AUTOREV in SRCREV

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#15]

**Comment by macpijan** [comment]
I would be very happy to use that feature. Does anyone have an idea what's the current state and where should we look to implement that?

**Comment by macpijan** [comment]
In Yocto, it is defined in meta/bitbake.conf as: `AUTOREV = "${@bb.fetch2.get_autorev(d)}"`

We can also define it in here. I have added it in my recipe to test and it works as anticipated.

**Comment by ismagulb** [comment]
Thanks for testing! Care to submit a patch to isar-users@googlegroups.com?

**Comment by macpijan** [comment]
https://groups.google.com/forum/#!topic/isar-users/kAPbek2QdxQ

**Comment by myo73** [comment]
Fixed in commit b2d9cc6
