### ISSUE TITLE
wic does not find mkdosfs

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#17]
Date: Thu, 29 Jun 2017 17:52:24 +0200
From: Jan Kiszka
To: isar-users <isar-users@googlegroups.com>

...because users do not have /sbin in their PATH. Where to fix this best? I don't want to fork imported wic files.

**Comment by henning-schild** [comment]
fixed by now, we use utils from buildchroot

a8a7e5d7a03138291d8a0a948ffbc3e3ddc543a8
