### ISSUE TITLE
IMAGE_TYPE = "wic"

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#18]
Date: Thu, 29 Jun 2017 17:52:24 +0200
From: Jan Kiszka
To: isar-users <isar-users@googlegroups.com>

I'm looking into IMAGE_TYPE = "wic" so that the user no longer has to call wic explicitly. We do this successfully in the yocto layer meta-iot2000 for quite a while.

**Comment by henning-schild** [comment]
fixed in a8a7e5d7a03138291d8a0a948ffbc3e3ddc543a8 ?
