### ISSUE TITLE
Determine kernel version

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#30]
Currently, the kernel version is hard-coded in the multiconfig file. Whenever Debian releases a new revision, the multiconfig file has to be updated. 52b8d35 determines the version automatically. It should be rebased onto the current master and updated to cover all multiconfigs.

Further use cases:

* Multiple versions in Debian.
* Additional kernels in product repos.
* Kernel not installed into the rootfs.
* No initrd.

**Comment by ismagulb** [comment]
1. No AI: Multiple versions in Debian: Choosing via package name in IMAGE_INSTALL, the script determines the file name OOTB.
2. No AI: Additional kernels in product repos: Choosing via package name in IMAGE_INSTALL. If the kernel package follows the Debian vmlinuz -> boot/vmlinuz-a.b.c-d (recommended), the script would determine the file name OOTB. If the kernel package doesn't create the vmlinuz symlink (not recommended), it is still possible to specify KERNEL_IMAGE and INITRD_IMAGE vars, as it is now.
3. TODO: Kernel not installed into the rootfs: The script currently doesn't handle missing /vmlinuz, bitbake will fail.
4. TODO: No initrd: The same as 3 above.

**Comment by alexbluesman** [comment]
Script handles the cases 3 and 4.

**Comment by alexbluesman** [comment]
All the items are provided by commit: fbdaf68f4ce849ef0f6fa4c05ebee8e61f51a13f
