### ISSUE TITLE
[Bug] Armhf build errors on VM running on Mac OS X

### ISSUE THREAD

**Issue by elfgoh** [ilbers/isar#31]
# Problem description.
Following the [user manual steps](https://github.com/ilbers/isar/blob/master/doc/user_manual.md) and running them in a Debian Stretch Virtualbox VM using Vagrant on Mac OS X 10.12.6, is unsuccessful

# Expected / desired behavior.
Expecting a successful build

# Actual behavior.
Build fails. Error msg

```
chroot: failed to run command ‘/configscript.sh’: Exec format error
WARNING: exit code 126 from a shell command.
```

# How to reproduce.
- Install vagrant and virtualbox 
```
vagrant box add debian/stretch64
vagrant init debian/stretch64
vagrant ssh
git clone http://github.com/ilbers/isar.git
cd isar/
. isar-init-build-env ../build
time bitbake isar-image-base isar-image-debug
```

**Comment by ismagulb** [comment]
Thanks! :)

**Comment by elfgoh** [comment]
This issue persists when running `next` branch, and the default `local.conf` file

**Comment by elfgoh** [comment]
When changing `MACHINE` from `armhf` to`amd64`, the build resumes and succeeds

**Comment by elfgoh** [comment]
Seems like there are some network errors messages when I scrolled up earlier in the logfile. I will tackle them and update

**Comment by elfgoh** [comment]
Build successful.
