### ISSUE TITLE
do_ext4_image: mkdir: cannot create directory '.../tmp/deploy/images': File exists

### ISSUE THREAD

**Issue by ismagulb** [ilbers/isar#32]
asmirnov/next 6f689d7

[console.txt](https://github.com/ilbers/isar/files/1393855/console.txt)
[log.do_ext4_image.1276.txt](https://github.com/ilbers/isar/files/1393860/log.do_ext4_image.1276.txt)

**Comment by alexbluesman** [comment]
There was races between tasks: `do_copy_boot_files` and `do_ext4_image`. Fixed in the same branch.

**Comment by ismagulb** [comment]
asmirnov/next bfe9d1f

[console2.txt](https://github.com/ilbers/isar/files/1395726/console2.txt)

**Comment by alexbluesman** [comment]
Please try.

Output:
-------------------------------------------------
Testing Isar [wheezy] image for [arm] machine:
Test: FAIL
-------------------------------------------------
Testing Isar [jessie] image for [arm] machine:
Test: PASSED
-------------------------------------------------
Testing Isar [stretch] image for [arm] machine:
Test: FAIL
-------------------------------------------------
Testing Isar [jessie] image for [amd64] machine:
Test: PASSED
-------------------------------------------------
Testing Isar [stretch] image for [amd64] machine:
Test: PASSED
-------------------------------------------------
Testing Isar [jessie] image for [i386] machine:
Test: PASSED
-------------------------------------------------
Testing Isar [stretch] image for [i386] machine:
Test: PASSED

**Comment by ismagulb** [comment]
asmirnov/next 43f9a99 builds.
