### ISSUE TITLE
[Doc]Does start_armhf_vm command work?

### ISSUE THREAD

**Issue by elfgoh** [ilbers/isar#33]
I saw it in the project README. Should `start_armhf_vm` be `start_vm`?

**Comment by alexbluesman** [comment]
Hi,

yes, you are right. Please use `start_vm` script to run QEMU images. Try `-h`  parameter to see all the supported option.

For example, to start ARM jessie: `start_vm -a arm -d jessie`

**Comment by elfgoh** [comment]
The command succeeds but I did not get a successful run:
```
$ start_vm -a amd64 -d jessie
IMAGE_DIR=/home/luther/isar_project/build/tmp/deploy/images; \
qemu-system-x86_64 \
    -m 1024M \
    -M pc \
    \
    -nographic \
    -kernel $IMAGE_DIR/vmlinuz-3.16.0-4-amd64 \
    -initrd $IMAGE_DIR/initrd.img-3.16.0-4-amd64 \
    -append "console=ttyS0 root=/dev/sda rw" \
    -hda $IMAGE_DIR/isar-image-base-qemuamd64-debian-jessie.ext4.img
qemu: could not load kernel '/home/luther/isar_project/build/tmp/deploy/images/vmlinuz-3.16.0-4-amd64': No such file or directory

$ ls  `/home/foo/isar_project/build/tmp/deploy/images/`
isar-image-base-qemuamd64-debian-jessie.ext4.img
```

**Comment by alexbluesman** [comment]
Could you please provide your build command. Also I see that your make `ls`  in different folder than IMAGE_DIR

**Comment by elfgoh** [comment]
Lol i thought maybe I wanna hide my user id but nvm

**Comment by elfgoh** [comment]
The build command is `$ bitbake isar-image-base`

**Comment by elfgoh** [comment]
I remove `build` directory and rebuild using `bitbake isar-image-base`. Note that I am now on `asmirnov/next`branch 

```
luther@debian:~/isar_project/build$ start_vm -a arm -d jessie
IMAGE_DIR=/home/luther/isar_project/build/tmp/deploy/images; \
qemu-system-arm \
    -m 1024M \
    -M virt \
    -cpu cortex-a15\
    -nographic \
    -kernel $IMAGE_DIR/vmlinuz-3.16.0-4-armmp \
    -initrd $IMAGE_DIR/initrd.img-3.16.0-4-armmp \
    -append "console=ttyAMA0 root=/dev/vda rw" \
    -drive file=$IMAGE_DIR/isar-image-base-qemuarm-debian-jessie.ext4.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0
/home/luther/isar_project/build/tmp/deploy/images/vmlinuz-3.16.0-4-armmp: No such file or directory
qemu: could not load kernel '/home/luther/isar_project/build/tmp/deploy/images/vmlinuz-3.16.0-4-armmp'
luther@debian:~/isar_project/build$
```

**Comment by alexbluesman** [comment]
Isar uses multiconfig to support various distros and architectures. The full supported list could be found here: https://github.com/ilbers/isar/blob/master/doc/user_manual.md#building-target-images-for-multiple-configurations

So, for ARM jessie, the build command should be:

```
$ bitbake multiconfig:qemuarm-jessie:isar-image-base
```

**Comment by elfgoh** [comment]
I see. I was referring to the [README](https://github.com/ilbers/isar/blob/asmirnov/next/doc/user_manual.md) `Building Target Images for One Configuration`.  I am assuming that the instructions under `Building Target Images for One Configuration` are no longer relevant, and that I should always go with the multiconfig build command?

2nd question. If I do a build using ` bitbake multiconfig:qemuarm-jessie:isar-image-base`, should I remove the existing `build` directory?

**Comment by ismagulb** [comment]
> I see. I was referring to the README Building Target Images for One Configuration. I am assuming that the instructions under Building Target Images for One Configuration are no longer relevant, and that I should always go with the multiconfig build command?

Unfortunately, yes (#24).

> 2nd question. If I do a build using bitbake multiconfig:qemuarm-jessie:isar-image-base, should I remove the existing build directory?

As long as you haven't modified the isar directory, I think you don't need to delete the build directory. Alex, please correct me if I'm wrong.

**Comment by elfgoh** [comment]
Seems that at the very least, the build command didnt work. I am deleting `build` directory to see if it makes a difference

```
luther@debian:~/isar_project/isar$ git checkout next
Switched to branch 'next'
luther@debian:~/isar_project/isar$ cd ..
luther@debian:~/isar_project$ cd build/
luther@debian:~/isar_project/build$ bitbake multiconfig:qemuarm-jessie:isar-image-base
NOTE: Not using a cache. Set CACHE = <directory> to enable.
Parsing recipes: 100% |##################################################| Time: 0:00:00
Parsing of 4 .bb files complete (0 cached, 4 parsed). 36 targets, 0 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |###############################################| Time: 0:00:00
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 9 tasks of which 9 didn't need to be rerun and all succeeded.
luther@debian:~/isar_project/build$ start_vm -a arm -d jessie
IMAGE_DIR=/home/luther/isar_project/build/tmp/deploy/images; \
qemu-system-arm \
    -m 1024M \
    -M virt \
    -cpu cortex-a15\
    -nographic \
    -kernel $IMAGE_DIR/vmlinuz-3.16.0-4-armmp \
    -initrd $IMAGE_DIR/initrd.img-3.16.0-4-armmp \
    -append "console=ttyAMA0 root=/dev/vda rw" \
    -drive file=$IMAGE_DIR/isar-image-base-qemuarm-debian-jessie.ext4.img,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0
/home/luther/isar_project/build/tmp/deploy/images/vmlinuz-3.16.0-4-armmp: No such file or directory
qemu: could not load kernel '/home/luther/isar_project/build/tmp/deploy/images/vmlinuz-3.16.0-4-armmp'
luther@debian:~/isar_project/build$
```

**Comment by elfgoh** [comment]
@ismagulb sorry if I am ignorant, but I fail to understand why #24 is related to the need to use the multiconfig build command. Please kindly elaborate

**Comment by alexbluesman** [comment]
Yes, please try clean build in new terminal (to avoid possible issues with environment):
1. cd isar
2. source isar-init-build-env
3. bitbake multiconfig:qemuarm-jessie:isar-image-base

**Comment by elfgoh** [comment]
Thanks for the help! Successfully build and ran the qemu image. I will send a PR to the docs before closing this

**Comment by alexbluesman** [comment]
Just to avoid duplications, I've already sent the patches to the list: https://groups.google.com/forum/#!topic/isar-users/CYPrufepyYU
https://groups.google.com/forum/#!topic/isar-users/guoHFJqI0JE

**Comment by elfgoh** [comment]
Great! I am not so familiar with patches, compared to pull requests. Is sending patches to the mailing way the preferred workflow, rather than via pull requests?

**Comment by alexbluesman** [comment]
Documentation updated, commit: 5193b44f0fd55ca5dedc18da8b961625a98d1c56
