### ISSUE TITLE
[Question] Which project branches is recommended for use?

### ISSUE THREAD

**Issue by elfgoh** [ilbers/isar#35]
The project has [12 branches](https://github.com/ilbers/isar/branches). And at one point @alexbluesman advised me to use `asmirnov/next`, though he has edited that to `next`

Question: Is it best to just always use `next` branch as using `master seems to be problematic?

**Comment by alexbluesman** [comment]
No, `asmirnov/next` is not the reference branch. As mentioned in https://github.com/ilbers/isar/blob/next/doc/maintainer.md, there are two branches: `next` and `master`. For the latest staging state please use the first one.
