### ISSUE TITLE
mount refactoring

### ISSUE THREAD

**Issue by stormc** [ilbers/isar#38]
As `bitbake/lib/bb/build.py`'s `shell_trap_code()` injects `set -e` into scripts, the premature end of scripts leaves dangling mounts around. This may be fixed by hooking into the `EXIT` trap handler also setup by `shell_trap_code()`. See the patch and discussion on the [Mailing List](https://groups.google.com/forum/#!topic/isar-users/2CVvYFc0pqY) for details.

Currently, by the patches sent to the Mailing List, dangling mount handling is local to the scripts. Eventually, a more thorough approach may be taken, e.g., based on [this proposal](https://groups.google.com/forum/#!msg/isar-users/2CVvYFc0pqY/XQeXLFVWAQAJ) using an "unmount stack".

**Comment by alexbluesman** [comment]
Implemented via bitbake events.
