### ISSUE TITLE
ISAR does not build on ubuntu 18.04 

### ISSUE THREAD

**Issue by stulluk** [ilbers/isar#41]
root@sertac-build:/DATA/ISAR-Test2# **git clone https://github.com/ilbers/isar.git**
Cloning into 'isar'...
remote: Counting objects: 4069, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 4069 (delta 27), reused 39 (delta 22), pack-reused 4020
Receiving objects: 100% (4069/4069), 18.03 MiB | 5.31 MiB/s, done.
Resolving deltas: 100% (2124/2124), done.
root@sertac-build:/DATA/ISAR-Test2# ^C

root@sertac-build:/DATA/ISAR-Test2# cd isar/

root@sertac-build:/DATA/ISAR-Test2/isar# **. isar-init-build-env ../build**
You had no conf/local.conf file. This configuration file has therefore been
created for you with some default values. You may wish to edit it to, for
example, select a different MACHINE (target hardware). See conf/local.conf
for more information as common configuration options are commented.

You had no conf/bblayers.conf file. This configuration file has therefore been
created for you with some default values. To add additional metadata layers
into your configuration please add entries to conf/bblayers.conf.

For more information about isar, contact the developers at:
    https://lists.debian.org/debian-embedded/

### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    isar-image-base
    isar-image-debug
root@sertac-build:/DATA/ISAR-Test2/build# **bitbake -s**
Traceback (most recent call last):
  File "/DATA/ISAR-Test2/isar/bitbake/bin/bitbake", line 31, in <module>
    import bb
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/__init__.py", line 79, in <module>
    from bb import fetch2 as fetch
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/fetch2/__init__.py", line 1846, in <module>
    from . import clearcase
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/fetch2/clearcase.py", line 72, in <module>
    from   distutils import spawn
ImportError: cannot import name 'spawn'
root@sertac-build:/DATA/ISAR-Test2/build# **bitbake isar-image-base**
Traceback (most recent call last):
  File "/DATA/ISAR-Test2/isar/bitbake/bin/bitbake", line 31, in <module>
    import bb
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/__init__.py", line 79, in <module>
    from bb import fetch2 as fetch
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/fetch2/__init__.py", line 1846, in <module>
    from . import clearcase
  File "/DATA/ISAR-Test2/isar/bitbake/lib/bb/fetch2/clearcase.py", line 72, in <module>
    from   distutils import spawn
ImportError: cannot import name 'spawn'
root@sertac-build:/DATA/ISAR-Test2/build# ^C
root@sertac-build:/DATA/ISAR-Test2/build#

**Comment by kendalla59** [comment]
I had a similar problem that I solved with:
% sudo apt install python3-distutils

Now I'm running into issues compiling QEMU due to more stringent error checking with GCC on Ubuntu 18.04 (gcc-7). If you figure that one out I would love to see your solution.

**Comment by henning-schild** [comment]
@kendalla59 there should be no need to compile qemu

A lot of Isar users use docker to abstract away from differences in host distros.
https://groups.google.com/forum/#!topic/isar-users/Ve4ctIZKhac
https://hub.docker.com/r/kasproject/kas-isar/
