### ISSUE TITLE
[Question] What is the roadmap for Debian 9 support?

### ISSUE THREAD

**Issue by elfgoh** [ilbers/isar#42]
Currently the main page readme says only Debian 8 is supported. May I know what are the plans for supporting Debian 9 if any?

**Comment by alexbluesman** [comment]
Hello! Debian stretch is already supported, here you could find of the supported configurations:
https://github.com/ilbers/isar/blob/master/scripts/ci_build.sh#L75

**Comment by henning-schild** [comment]
can that be closed?
