### ISSUE TITLE
Environment variable DL_DIR being overwritten

### ISSUE THREAD

**Issue by Silvanoc** [ilbers/isar#43]
Specifying the environment variable DL_DIR doesn't work as expected, because ISAR default bitbake configuration overwrites it. `DL_DIR = "` is being used instead of `DL_DIR ?= "`.

**Comment by Silvanoc** [comment]
> Are you sure your expectation is correct and whatever you are trying to do would work i.e. in openembedded?

I have to admit, that I never checked it.

But I appear not to be the only one with that expectation. Since the project [KAS](https://github.com/siemens/kas) is giving the environment variable DL_DIR enough importance to pass it to bitbake. See the [documentation here](https://kas.readthedocs.io/en/0.19.0/userguide.html#environment-variables) and the [code here](https://github.com/siemens/kas/blob/ecbda0494befeeb1e1f6e827c9ae12779daa24f0/kas/libkas.py#L255).

@igaw you [initially implemented support for it on KAS](https://github.com/siemens/kas/commit/daf0abab5e0c61d81eee1c6ad69a8040adc2c187#diff-219df6ca81bbfcb27a6ed4b19f61b148R168), does it mean that you agree on my expectation? :smiley:

**Comment by igaw** [comment]
kas passes DL_DIR through and those Yocto project I am working on honor the environment variable. Why should DL_DIR be hard coded in the project. That doesn't make sense to me. This is something the build setup needs to control not the upstream project.

**Comment by Silvanoc** [comment]
According to the bitbake [upstream documentation](https://www.yoctoproject.org/docs/1.6/bitbake-user-manual/bitbake-user-manual.html#idm45023932077824), this variable should be honored. So I would expect ISAR also to honor it too. Since ISAR is not honoring it, I would expect it to be either a bitbake bug or an ISAR bug.

> In fact there are two assignments using the = operator in build/conf/bitbake.conf but one of them is coming from upstream bitbake.

@henning-schild do you mean [this for Bitbake](https://github.com/openembedded/bitbake/blob/8efa7826a61501589afa33eb698c0ab3a622bf2e/conf/bitbake.conf#L26) and [this for ISAR](https://github.com/ilbers/isar/blob/39e0c488d8b2d80006af2a7451c966193047b4e8/bitbake/conf/bitbake.conf#L26)?

**Comment by Silvanoc** [comment]
@henning-schild you're right. Too much context switching with leftovers from other contexts :smile: Closing here and moving to the mailing list
