### ISSUE TITLE
Native git protocol for hello.git does not work

### ISSUE THREAD

**Issue by johann-pfefferl** [ilbers/isar#5]
Instead use http/https protocol instead

**Comment by johann-pfefferl** [comment]
I use the entry

SRC_URI = "git://github.com/ilbers/hello.git;protocol=https"

fetch the repo.

**Comment by alexbluesman** [comment]
Am I right that you work under proxy, which blocks git protocol traffic?

**Comment by Silvanoc** [comment]
Yes, we have a proxy that blocks the git protocol 👎
