### ISSUE TITLE
Memcached Injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [ilbers/isar#58]
We found a problem about Memcached Injection in isar-master/bitbake/lib/toaster/toastergui/typeaheads.py 
![image](https://user-images.githubusercontent.com/39950310/60805999-6740dc80-a1b4-11e9-868d-502b82c49952.png)
Invoking a Memcached operation with input coming from an untrusted source might allow an attacker to introduce new key/value pairs in Memcached cache.

**Comment by ismagulb** [comment]
Thanks for the report, we'll have a look.

**Comment by ismagulb** [comment]
bitbake is a copy of an external package, the issue must be addressed there.
