### ISSUE TITLE
Building of hello demo failed

### ISSUE THREAD

**Issue by johann-pfefferl** [ilbers/isar#6]
Error log:

==================================================================
ERROR: hello-1.0-r0 do_unpack: Build of do_unpack failed
ERROR: hello-1.0-r0 do_unpack: Traceback (most recent call last):
  File "/home/pfefferl/projects/isar/bitbake/lib/bb/build.py", line 642, in exec_task
    return _exec_task(fn, task, d, quieterr)
  File "/home/pfefferl/projects/isar/bitbake/lib/bb/build.py", line 580, in _exec_task
    exec_func(task, localdata)
  File "/home/pfefferl/projects/isar/bitbake/lib/bb/build.py", line 210, in exec_func
    bb.utils.mkdirhier(adir)
  File "/home/pfefferl/projects/isar/bitbake/lib/bb/utils.py", line 740, in mkdirhier
    raise e
  File "/home/pfefferl/projects/isar/bitbake/lib/bb/utils.py", line 737, in mkdirhier
    os.makedirs(directory)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/pfefferl/projects/isar/build/tmp/work/buildchroot/debian-stretch/rootfs//home/builder'

ERROR: Task (multiconfig:qemu-amd64:/home/pfefferl/projects/isar/meta-isar/recipes-app/hello/hello.bb:do_unpack) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4 tasks of which 3 didn't need to be rerun and 1 failed.
============================================================================

The mentions directory "..../home/builder" does really not exist!!

**Comment by ismagulb** [comment]
Thanks, will have a look.

**Comment by alexbluesman** [comment]
Hello!
Could you please specify the following details:
 - Your host: Linux distro, 32/64-bit
 -  The command you use to build Isar

Thank you,
Alex

**Comment by johann-pfefferl** [comment]
Linux distro: Standard Debian jessie installation inside a VM
Command: bitbake multiconfig:qemu-amd64:isar-image-base
Branch: lenormf/uefi_wic_amd64-20170428

**Comment by ismagulb** [comment]
Standard Debian jessie installation inside a VM: 64-bit

**Comment by alexbluesman** [comment]
According to the log, looks like there is `sudo` problem. Could you please provide the following:
1. `ls -l tmp/work/buildchroot/debian-stretch/rootfs/home`
2. `sudo cat /etc/sudoers | grep pfefferl`
3. Check that `sudo mkdir test` works without password

**Comment by johann-pfefferl** [comment]
ls -l tmp/work/buildchroot/debian-stretch/rootfs/home
total 0

Better use "sudo -l" to get the real answer of sudo because configuration can also be stored in subdirectory "/etc/sudoers.d".

Matching Defaults entries for pfefferl on isard:
    env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin

User pfefferl may run the following commands on isard:
    (root) NOPASSWD: ALL

According to the above output sudo allows all commands to execute as root without password. The "mkdir" test works in my setup.

**Comment by johann-pfefferl** [comment]
I made a step forward.

After doing

apt-get install automake autoconf libtool

I got rid of this "mkdir" problem. It would be nice to mention the required packages at the beginning of the README file.

But now I have the next problem to build the demo. See attached log file.
[log.do_build.23127.txt](https://github.com/ilbers/isar/files/985952/log.do_build.23127.txt)

**Comment by johann-pfefferl** [comment]
If I do the following

cd tmp/work/buildchroot/debian-stretch/rootfs/home/builder/hello/git && autoreconf

and then do a

bitbake multiconfig:qemu-amd64:isar-image-base

the whole thing builds.

So it seems that the hello demo autoconf setup is broken or not consistent regarding the used versions.

**Comment by johann-pfefferl** [comment]
Another possible reason for this behaviour is a missing dependency between the buildchroot and the "hello demo" task inside bitbake.

If I set the variable

BB_NUMBER_THREADS = "1"

and switch my virtual machine to a single core by offlining all other cpus

chcpu -d 1,2,3

then the problem does not occur or at least not so often.

**Comment by ismagulb** [comment]
Hello Hans,

please see lenormf/uefi_wic_amd64-20170428 e5cf95f.

Otherwise, you can always remove hello from IMAGE_INSTALL in builddir/conf/local.conf.

Please let me know whether the fix worked for you.

**Comment by johann-pfefferl** [comment]
The commit e5cf95f07b4eb718537a3918c7dbe411ce030be1 fixed the problem.

**Comment by ismagulb** [comment]
Hans, thanks for testing!

I'd like to keep the issue open in order to:

1. Fix the mkdir problem, if still relevant, and

2. Close when merged to master.

**Comment by ismagulb** [comment]
The `mkdir` issue should be solved in the scope of #11.
