### ISSUE TITLE
kernel softlink in rootfs is misleading for mips/powerpc

### ISSUE THREAD

**Issue by hberneck** [ilbers/isar#61]
For mips and powerpc the created softlink is allways wrong.
-> do_copy_boot_files fails

Isar creates a softlink for vmlinuz (build-kernel.sh)
The kernel installs vmlinux into the debian package (scripts/package/builddeb)

**Comment by jan-kiszka** [comment]
Check the mailing list, there are patches to address MIPS issues flying around.

**Comment by ismagulb** [comment]
@hberneck, the mentioned patches have been integrated, does this solve your issue?

**Comment by hberneck** [comment]
It was solved by the commits "meta: image: Account for Ubuntu differences in do_copy_boot_files" and "linux-custom: rewrite to no longer depend on the kernel's builddeb".
THX
