### ISSUE TITLE
DISTRO_APT_PREMIRRORS broken?

### ISSUE THREAD

**Issue by vj-kumar** [ilbers/isar#62]
Hi All,

DISTRO_APT_PREMIRRORS has no effect on the final wic image. buildchroot-target/host & isar-bootstrap-target/host has the preferred mirrors as specified in DISTRO_APT_PREMIRRORS but the final image does not seem to have it.

Steps to reproduce:  
Add the following lines to conf/local.conf  
DISTRO_APT_PREMIRRORS = "http://deb.debian.org/debian http://ftp.debian.org/debian"  
bitbake mc:qemuamd64-buster:isar-image-base  

Thanks,  
Vijai Kumar K

**Comment by vj-kumar** [comment]
Tested and works on v0.7

**Comment by jan-kiszka** [comment]
Please report to the list. I think we need to discuss there if the current behavior isn't the desired one.

**Comment by vj-kumar** [comment]
Closing the issue. Relevant mailing list discussion below.  

https://groups.google.com/forum/#!topic/isar-users/uaBORl00HHA
