### ISSUE TITLE
wic tools fails on Debian jessie

### ISSUE THREAD

**Issue by johann-pfefferl** [ilbers/isar#8]
The wic tool calls mkfs.ext4 with option "-d". This option does not exist in the Debian jessie version. So it should be mentioned in the readme file that at least Debian stretch is required.

**Comment by johann-pfefferl** [comment]
Moreover it should be mentioned that a

export PATH=$PATH:/sbin

is necessary as normal user for some system relvant tools.

**Comment by jan-kiszka** [comment]
The second issue should be solved by https://groups.google.com/forum/#!topic/isar-users/6EjeGHH-Krc.

**Comment by ismagulb** [comment]
Documented in 4da6d15 and 8378b39, respectively.

**Comment by jan-kiszka** [comment]
You didn't comment on the fix for the isar-init-build-env script on the list nor applied it. Addressing by documentation is an inferior solution IMHO.

**Comment by ismagulb** [comment]
Oops, overlooked, thanks for reminding. The next time, please re-open the issue. Expect a merge.

**Comment by jan-kiszka** [comment]
Only privileged people can reopen tickets - I can't.

**Comment by ismagulb** [comment]
Hmm, couldn't find any settings regarding re-opening, seems to be hard-coded. But the comments are also sent by mail, so we should track it manually.

**Comment by ismagulb** [comment]
The second one done in 19ae523.

**Comment by henning-schild** [comment]
With the integration of wic you should be able to build >=stretch images on jessie. Jessie images can not be build, because of the first issue.
Can be closed?
