### ISSUE TITLE
linux-modules/modules.inc doesn't expand AUTOLOAD correctly

### ISSUE THREAD

**Issue by torstenchr** [ilbers/isar#81]
If the AUTOLOAD variable has more than 1 entry the for-loop in do_prepare_build() doesn't expand and therefor result in a one-line entry into the postinst file. This in turn gives the wrong format for the /etc/modules (all module names are on the same line) and therefor fails to load at startup.

Fix for the issue has been attached.
[modules.inc.patch.gz](https://github.com/ilbers/isar/files/8169444/modules.inc.patch.gz)

**Comment by jan-kiszka** [comment]
Thanks for the fix. Could you send it to the mailing list for review? git-send-email, i.e. inlined and signed-off. TIA!

**Comment by amikan** [comment]
The fix was already applied to master, so closing the issue
