### ISSUE TITLE
Enable non-root building - again

### ISSUE THREAD

**Issue by mr-nice** [ilbers/isar#84]
Hi all,

Are there any efforts or updates to #11? Just closing it will not remove the issue?

The readme still contains the sudo ALL=NOPASSWD: ALL

Openembedded/yocto is able to build distributions with pseudo just fine. What is the actual problem with pseudo here?

Has anyone looked at using [polystrap](https://github.com/josch/polystrap) instead of debootstrap? Also debians CrossDebootstrap has a section for building images as non root user. (also using multistrap)

I saw some approaches using privileged containers but that seam just to "hide" the issue?

1: https://github.com/josch/polystrap
2: https://wiki.debian.org/EmDebian/CrossDebootstrap#Generating_cross_images_as_non-root_user

**Comment by mr-nice** [comment]
There is also mmdebstrap as more or less drop in replacement
https://gitlab.mister-muffin.de/josch/mmdebstrap

**Comment by ismagulb** [comment]
Let's continue in #11.
