### ISSUE TITLE
sstate-cache support

### ISSUE THREAD

**Issue by yli147** [ilbers/isar#86]
It looks as default SSTATE_DIR is not set to ${TMPDIR}/sstate-cache. And there is no sstate-cache generated when I use isar, anyone here can get the sstate-cache ?

**Comment by amikan** [comment]
Hello @yli147,
Default `SSTATE_DIR` value is set to `${TOPDIR}/sstate-cache` in `meta/conf/bitbake.conf`.
It means you should look for it one level upper, like: `<isar_dir>/build/sstate-cache`.

**Comment by yli147** [comment]
Thanks, root caused,  we were using old isar version cuased the issue.
