### ISSUE TITLE
x86 build fails with wrong linux kernel version

### ISSUE THREAD

**Issue by johann-pfefferl** [ilbers/isar#9]
The kernel package version has changed in the debian repository. So the build fails now.

Better to use package "linux-image-amd64" instead of versioned package. The same is with vmlinuz and initrd. Better use /vmlinuz and /initrd.img instead of versioned names from /boot directory.

**Comment by johann-pfefferl** [comment]
Here is the log file
[log.do_rootfs.597.txt](https://github.com/ilbers/isar/files/1019092/log.do_rootfs.597.txt)

**Comment by alexbluesman** [comment]
Done, commit: fbdaf68f4ce849ef0f6fa4c05ebee8e61f51a13f
