### ISSUE TITLE
do_rootfs_quality_check reports warnings when adding >1 new users

### ISSUE THREAD

**Issue by developerdong** [ilbers/isar#98]
# Problem description

```sh
WARNING: img-1.0-r0 do_rootfs_quality_check: Files changed after package install. The following files seem
WARNING: img-1.0-r0 do_rootfs_quality_check: to have changed where they probably should not have.
WARNING: img-1.0-r0 do_rootfs_quality_check: You might have a custom task or writing POSTPROCESS function.
WARNING: img-1.0-r0 do_rootfs_quality_check: /build/tmp/work/debian-bullseye-amd64/img-vmware/1.0-r0/rootfs/etc/subgid-
/build/tmp/work/debian-bullseye-amd64/img-vmware/1.0-r0/rootfs/etc/subuid-
/build/tmp/work/debian-bullseye-amd64/img-vmware/1.0-r0/rootfs/etc/passwd-
```

When add >1 new users in bb files, `do_rootfs_quality_check` reports this warning.
For example:

`USERS = "user1"` is fine, because it only creates one new user.
`USERS = "user1 user2"` is problematic, because it creates two new users.
`USERS = "user1 daemon"` is fine, because daemon is an existing user, only user1 is newly created.
`USERS = "user1 user2 daemon"` is not ok, because there are still two new users except for daemon.

# Expected / desired behavior

No warnings when adding >1 new users.

# Actual behavior

There are warnings.

# How to reproduce

Add `USERS += "user1 user2"` in your bb files, build it, then you can see the warnings.

# Possible root cause

Here is the print when I execute `useradd` in a debian 11 docker container.

```bash
root@c2b0dff21c2f:/# ls -l /etc/ | grep -E 'passwd|sub' 
-rw-r--r-- 1 root root     922 Dec 19  2022 passwd
-rw-r--r-- 1 root root     922 Dec 19  2022 passwd-
-rw-r--r-- 1 root root       0 Dec 19  2022 subgid
-rw-r--r-- 1 root root       0 Dec 19  2022 subuid
root@c2b0dff21c2f:/# useradd user1
root@c2b0dff21c2f:/# ls -l /etc/ | grep -E 'passwd|sub' 
-rw-r--r-- 1 root root     961 Oct 19 03:56 passwd
-rw-r--r-- 1 root root     922 Dec 19  2022 passwd-
-rw-r--r-- 1 root root      19 Oct 19 03:56 subgid
-rw-r--r-- 1 root root       0 Dec 19  2022 subgid-
-rw-r--r-- 1 root root      19 Oct 19 03:56 subuid
-rw-r--r-- 1 root root       0 Dec 19  2022 subuid-
root@c2b0dff21c2f:/# useradd user2
root@c2b0dff21c2f:/# ls -l /etc/ | grep -E 'passwd|sub' 
-rw-r--r-- 1 root root    1000 Oct 19 03:56 passwd
-rw-r--r-- 1 root root     961 Oct 19 03:56 passwd-
-rw-r--r-- 1 root root      38 Oct 19 03:56 subgid
-rw-r--r-- 1 root root      19 Oct 19 03:56 subgid-
-rw-r--r-- 1 root root      38 Oct 19 03:56 subuid
-rw-r--r-- 1 root root      19 Oct 19 03:56 subuid-
```
From the print, we can see that some files are created/changed.
In [image_create_users](https://github.com/ilbers/isar/blob/dff8ad504b54a4e292a1b986cdc74ebc9e6e177a/meta/classes/image-account-extension.bbclass#L126),  `useradd` is executed, which is indirectly included in ROOTFS_POSTPROCESS_COMMAND.

Meanwhile, `subgid-`, `subuid-`, and `passwd-` are not ignored in [do_rootfs_quality_check](https://github.com/ilbers/isar/blob/dff8ad504b54a4e292a1b986cdc74ebc9e6e177a/meta/classes/image.bbclass#L497).

# Possible solution

Ignore `subgid-`, `subuid-`, and `passwd-` in [do_rootfs_quality_check](https://github.com/ilbers/isar/blob/dff8ad504b54a4e292a1b986cdc74ebc9e6e177a/meta/classes/image.bbclass#L497).

**Comment by jan-kiszka** [comment]
Looks like a valid finding to me. Do you want to write such a patch and send it to the mailing list?

**Comment by amikan** [comment]
@developerdong thanks for detailed analysis, this really need to be fixed.
@jan-kiszka I will send a patch to the maillist soon if no objections.

**Comment by jan-kiszka** [comment]
@amikan I would have used that as training for a potential new contributor :wink: - if @developerdong is interested.
